@startuml

title "Messages - Sequence Diagram"

actor Seller
actor Buyer
entity MatchingEngine
entity ProductMatchingService
entity RuleMatchingService
entity ProductRulesService
entity ProductService

autoactivate on
Seller->ProductService: add products to db
return

Buyer->ProductRulesService: add product rules to db
return

Buyer->MatchingEngine: start matching
MatchingEngine->ProductService: get Products
return

MatchingEngine->ProductMatchingService: match against Product and threshold
ProductMatchingService->RuleMatchingService: match Rule condistions against Product attribvutes
RuleMatchingService->ProductRulesService: find rules for Product
return
ProductMatchingService->ProductMatchingService: consolidate match stats
return
return
return: return results for all rules for a product
return: filter and return results
Buyer->Buyer: Calculate totals and averages
Buyer->Buyer: Display
@enduml